#!/bin/bash

source $(dirname $0)/ggl.sh

print_usage() {
    print_text "NAME"
    print_text "    ggl - Show git log"
    print_text ""
    print_text "SYNOPSIS"
    print_text "    ggl [<options>] [--] [<pathspec>...]"
    print_text ""
    print_text "OPTIONS"
    print_text "    [<options>] [--] [<pathspec>...]"
    print_text "        Same as git log"
    print_text "    -h, --help"
    print_text "        Display this help message"
}

main() {
    git log --oneline --graph --all --decorate "$@"
}
